In [1]:
# Importing essential data manipulation and visualization libraries for the analysis.
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Loading the employee performance dataset and taking a quick look at the first few rows.
data=pd.read_csv("C:\\Users\\Dell\\OneDrive\\Desktop\\Project 1\\Extended_Employee_Performance_and_Productivity_Data\\Extended_Employee_Performance_and_Productivity_Data.csv", encoding="latin1")
data

,Employee_ID,Department,Gender,Age,Job_Title,Hire_Date,Years_At_Company,Education_Level,Performance_Score,Monthly_Salary,Work_Hours_Per_Week,Projects_Handled,Overtime_Hours,Sick_Days,Remote_Work_Frequency,Team_Size,Training_Hours,Promotions,Employee_Satisfaction_Score,Resigned
0,1,IT,Male,55,Specialist,2022-01-19 08:03:05.556036,2,High School,5,6750.0,33,32,22,2,0,14,66,0,2.63,False
1,2,Finance,Male,29,Developer,2024-04-18 08:03:05.556036,0,High School,5,7500.0,34,34,13,14,100,12,61,2,1.72,False
2,3,Finance,Male,55,Specialist,2015-10-26 08:03:05.556036,8,High School,3,5850.0,37,27,6,3,50,10,1,0,3.17,False
3,4,Customer Support,Female,48,Analyst,2016-10-22 08:03:05.556036,7,Bachelor,2,4800.0,52,10,28,12,100,10,0,1,1.86,False
4,5,Engineering,Female,36,Analyst,2021-07-23 08:03:05.556036,3,Bachelor,2,4800.0,38,11,29,13,100,15,9,1,1.25,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99996,Finance,Male,27,Technician,2022-12-07 08:03:05.556036,1,Bachelor,4,4900.0,55,46,5,3,75,16,48,2,1.28,False
99996,99997,IT,Female,36,Consultant,2018-07-24 08:03:05.556036,6,Master,5,8250.0,39,35,7,0,0,10,77,1,3.48,True
99997,99998,Operations,Male,53,Analyst,2015-11-24 08:03:05.556036,8,High School,2,4800.0,31,13,6,5,0,5,87,1,2.60,False
99998,99999,HR,Female,22,Consultant,2015-08-03 08:03:05.556036,9,High School,5,8250.0,35,43,10,1,75,2,31,1,3.10,False
99999,100000,Finance,Female,43,Analyst,2024-03-04 08:03:05.556036,0,PhD,1,4400.0,51,43,27,11,75,13,45,1,2.64,False

In [3]:
# Inspecting the tail end of the dataframe to verify record structures and indexing.
data.tail()

,Employee_ID,Department,Gender,Age,Job_Title,Hire_Date,Years_At_Company,Education_Level,Performance_Score,Monthly_Salary,Work_Hours_Per_Week,Projects_Handled,Overtime_Hours,Sick_Days,Remote_Work_Frequency,Team_Size,Training_Hours,Promotions,Employee_Satisfaction_Score,Resigned
99995,99996,Finance,Male,27,Technician,2022-12-07 08:03:05.556036,1,Bachelor,4,4900.0,55,46,5,3,75,16,48,2,1.28,False
99996,99997,IT,Female,36,Consultant,2018-07-24 08:03:05.556036,6,Master,5,8250.0,39,35,7,0,0,10,77,1,3.48,True
99997,99998,Operations,Male,53,Analyst,2015-11-24 08:03:05.556036,8,High School,2,4800.0,31,13,6,5,0,5,87,1,2.60,False
99998,99999,HR,Female,22,Consultant,2015-08-03 08:03:05.556036,9,High School,5,8250.0,35,43,10,1,75,2,31,1,3.10,False
99999,100000,Finance,Female,43,Analyst,2024-03-04 08:03:05.556036,0,PhD,1,4400.0,51,43,27,11,75,13,45,1,2.64,False

In [4]:
# Checking for any duplicate employee records to ensure data integrity.
data["Employee_ID"].duplicated().sum()

np.int64(0)

In [5]:
# Checking total rows, columns, and data types to identify any missing or mismatched values.
print("Data Column & Rows",data.shape)
print(data.info())

Data Column & Rows (100000, 20)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Employee_ID                  100000 non-null  int64
 1   Department                   100000 non-null  object
 2   Gender                       100000 non-null  object
 3   Age                          100000 non-null  int64
 4   Job_Title                    100000 non-null  object
 5   Hire_Date                    100000 non-null  object
 6   Years_At_Company             100000 non-null  int64
 7   Education_Level              100000 non-null  object
 8   Performance_Score            100000 non-null  int64
 9   Monthly_Salary               100000 non-null  float64
 10  Work_Hours_Per_Week          100000 non-null  int64
 11  Projects_Handled             100000 non-null  int64
 12  Overtime_Hours               100000 non-null  int64
 13  Sick_Days                    100000 non-null  int64
 14  Remote_Work_Frequency        100000 non-null  int64
 15  Team_Size                    100000 non-null  int64
 16  Training_Hours               100000 non-null  int64
 17  Promotions                   100000 non-null  int64
 18  Employee_Satisfaction_Score  100000 non-null  float64
 19  Resigned                     100000 non-null  bool
dtypes: bool(1), float64(2), int64(12), object(5)
memory usage: 14.6+ MB
None

In [6]:
# Re-verifying column data types after preprocessing steps.
data.dtypes

Employee_ID                      int64
Department                      object
Gender                          object
Age                              int64
Job_Title                       object
Hire_Date                       object
Years_At_Company                 int64
Education_Level                 object
Performance_Score                int64
Monthly_Salary                 float64
Work_Hours_Per_Week              int64
Projects_Handled                 int64
Overtime_Hours                   int64
Sick_Days                        int64
Remote_Work_Frequency            int64
Team_Size                        int64
Training_Hours                   int64
Promotions                       int64
Employee_Satisfaction_Score    float64
Resigned                          bool
dtype: object

In [7]:
# Counting total employee distribution across individual company departments.
data["Department"].value_counts()

Department
Marketing           11216
Finance             11200
Operations          11181
IT                  11131
Sales               11122
Legal               11118
Customer Support    11116
HR                  10960
Engineering         10956
Name: count, dtype: int64

In [10]:
# Calculating high-level workforce KPIs like overall headcount, attrition rate, and averages.
total_employee=data["Employee_ID"].count()
attrition_rate=data["Resigned"].sum()/total_employee
avg_monthly_salary=data["Monthly_Salary"].mean()
avg_satisfaction_score=data["Employee_Satisfaction_Score"].mean()
avg_performance_score=data["Performance_Score"].mean()
avg_overtime_hours=data["Overtime_Hours"].mean()
avg_tenure_yrs=data["Years_At_Company"].mean()
total_department=data["Department"].nunique()

In [11]:
# Displaying high-level workforce KPIs like overall headcount, attrition rate, and averages.
print("="*40)
print("""----------Workforce Overview &----------
-------Key Performance Indicators-------""")
print("="*40)
print()
print(f"Total Employees: {total_employee}")
print("Number of Departments: ",total_department)
print(f"Average Tenure Years: {avg_tenure_yrs:,.2f}Y")
print(f"Attrition Rate: {attrition_rate*100:,.2f}%")
print(f"Average Monthly Salary: ${avg_monthly_salary:,.2f}")
print(f"Average Satisfaction Score: {round(avg_satisfaction_score):,.2f}")
print(f"Average Performance Score: {round(avg_performance_score):,.2f}")
print(f"Average Overtime Hours: {avg_overtime_hours:,.2f} Hours")

========================================
----------Workforce Overview &----------
-------Key Performance Indicators-------
========================================

Total Employees: 100000
Number of Departments:  9
Average Tenure Years: 4.48Y
Attrition Rate: 10.01%
Average Monthly Salary: $6,403.21
Average Satisfaction Score: 3.00
Average Performance Score: 3.00
Average Overtime Hours: 14.51 Hours

In [12]:
from sqlalchemy import create_engine

username= "root"
password= "Shadabfarooqui123"
host= "localhost"
port= "3306"
database= "projects"

engine= create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

table_name= "employee_dataset"
data.to_sql(table_name, engine, if_exists="replace", index=False)

100000